spring:
  datasource:
    username: root
    password: Yrz991216@
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false



